version: '3.5'

services:
  db_users:
    image: postgres:16.3
    container_name: db_users
    env_file:
      - .env
    ports:
      - "6543:5432"
  redis:
    image: redis:7.2.5-bookworm
    container_name: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_ADMIN_ENABLE_SERVER: 'true'
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    depends_on:
      - zookeeper
    hostname: kafka
    env_file:
      - .env
    ports:
      - "29092:29092"